import { BookOpen, Sparkles, ExternalLink } from 'lucide-react';
import type { MedicalTerm } from '../data/medicalTerms';

export function SourcesSection({ terms }: { terms: MedicalTerm[] }) {
  return (
    <section className="rounded-2xl border border-pink-100 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-soft p-4 sm:p-5 animate-fade-in-up">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 bg-brand-100 dark:bg-brand-900/50 text-brand-600 dark:text-brand-300">
          <BookOpen className="w-5 h-5" />
        </div>
        <h3 className="text-base font-bold text-slate-800 dark:text-slate-100">Sources</h3>
      </div>

      {terms.length > 0 ? (
        <div className="mb-4">
          <p className="text-[11px] font-semibold text-slate-400 dark:text-slate-500 uppercase tracking-wide mb-2">
            Medical Terms Referenced
          </p>
          <div className="flex flex-wrap gap-2">
            {terms.map((t) => (
              <a
                key={t.term}
                href={t.wikipediaUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold bg-pink-50 dark:bg-slate-700 text-brand-700 dark:text-brand-300 hover:bg-pink-100 dark:hover:bg-slate-600 transition-colors"
              >
                {t.term}
                <ExternalLink className="w-3 h-3" />
              </a>
            ))}
          </div>
        </div>
      ) : (
        <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">
          No indexed medical terms were detected in this report.
        </p>
      )}

      <div className="flex items-start gap-2.5 p-3 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-800/40">
        <Sparkles className="w-4 h-4 text-amber-500 dark:text-amber-400 shrink-0 mt-0.5" />
        <p className="text-xs text-amber-700 dark:text-amber-300 leading-relaxed">
          This summary and term explanations were generated by AI for educational purposes.
          Wikipedia links are provided for general background reading and are not a substitute
          for advice from a licensed healthcare professional.
        </p>
      </div>
    </section>
  );
}
