export type Language = 'en' | 'hi' | 'ta';

export type UIStrings = {
  // Header
  header_subtitle: string;
  start_over: string;

  // Hero
  badge: string;
  heading_lab: string;
  heading_xray: string;
  desc_lab: string;
  desc_xray: string;

  // Report type toggle
  toggle_lab: string;
  toggle_xray: string;

  // Upload zone
  upload_lab: string;
  upload_xray: string;
  drag_drop: string;
  file_hint: string;

  // Feature badges
  badge_private: string;
  badge_instant: string;
  badge_plain: string;

  // Language selector
  lang_label: string;

  // Analyze button & loading
  analyze_lab: string;
  analyze_xray: string;
  analyzing_lab: string;
  analyzing_xray: string;
  steps_lab: string[];
  steps_xray: string[];
  try_again: string;

  // Results header
  file_name_fallback: string;
  analysis_complete: string;
  new_report: string;

  // Health risk card
  health_risk: string;
  risk_low: string;
  risk_moderate: string;
  risk_high: string;

  // Key findings
  key_findings: string;
  severity_normal: string;
  severity_monitor: string;
  severity_attention: string;

  // Report summary
  report_summary: string;

  // Abnormal values
  abnormal_values: string;
  no_abnormal: string;
  normal_range: string;

  // Questions
  questions_title: string;
  questions_subtitle: string;

  // Disclaimer
  disclaimer_title: string;
  disclaimer_1: string;
  disclaimer_2: string;
  disclaimer_3: string;
  disclaimer_4: string;

  // Sources section
  sources_title: string;
  medical_terms_referenced: string;
  no_terms: string;
  sources_disclaimer: string;

  // CTA + footer
  analyze_another: string;
  footer_disclaimer: string;

  // Errors
  error_image_type: string;
  error_image_size: string;
  error_not_configured: string;
  error_invalid_response: string;
  error_generic: string;
};

export const UI: Record<Language, UIStrings> = {
  // ── English ─────────────────────────────────────────────────────────────────
  en: {
    header_subtitle: 'Understand your report',
    start_over: 'Start over',

    badge: 'AI-assisted medical imaging',
    heading_lab: 'Understand your lab report\nin plain language',
    heading_xray: 'Understand your X-ray\nin plain language',
    desc_lab: 'Upload a photo of your lab report and get a clear summary, flagged values, and questions to bring to your doctor.',
    desc_xray: "Upload an X-ray image and get a plain-language explanation of what\u2019s visible, areas of concern, and questions to ask your doctor.",

    toggle_lab: 'Lab Report',
    toggle_xray: 'X-Ray',

    upload_lab: 'Tap to upload your report',
    upload_xray: 'Tap to upload your X-ray',
    drag_drop: 'or drag and drop an image here',
    file_hint: 'JPG, PNG \u00b7 up to 10 MB',

    badge_private: 'Private & secure',
    badge_instant: 'Instant analysis',
    badge_plain: 'Plain language',

    lang_label: 'Language',

    analyze_lab: 'Analyze Report',
    analyze_xray: 'Analyze X-Ray',
    analyzing_lab: 'Analyzing your report\u2026',
    analyzing_xray: 'Analyzing your X-ray\u2026',
    steps_lab: ['Extracting text from image', 'Sending to AI for analysis', 'Identifying abnormal values', 'Preparing your summary'],
    steps_xray: ['Processing X-ray image', 'Sending to AI radiologist', 'Identifying areas of concern', 'Preparing your explanation'],
    try_again: 'Try again',

    your_report: 'Your report',
    file_name_fallback: 'Uploaded report',
    analysis_complete: 'Analysis complete',
    new_report: 'New report',

    health_risk: 'Health Risk',
    risk_low: 'Low Risk',
    risk_moderate: 'Moderate Risk',
    risk_high: 'High Risk',

    key_findings: 'Key Findings',
    severity_normal: 'Normal',
    severity_monitor: 'Monitor',
    severity_attention: 'Attention',

    report_summary: 'Report Summary',

    abnormal_values: 'Abnormal Values',
    no_abnormal: 'No abnormal values detected. All results appear within normal ranges.',
    normal_range: 'Normal range:',

    questions_title: 'Questions to Ask Your Doctor',
    questions_subtitle: 'Bring these questions to your next appointment.',

    disclaimer_title: 'Disclaimer',
    disclaimer_1: 'This is not a medical diagnosis. Please consult a healthcare professional.',
    disclaimer_2: 'MediExplain is an informational tool and not a medical device. It does not diagnose, treat, or replace professional medical advice.',
    disclaimer_3: 'The analysis is generated by AI for educational purposes and may contain errors. Always consult a licensed healthcare provider before making decisions about your health.',
    disclaimer_4: 'By using this tool you acknowledge that the output is not a substitute for professional medical evaluation.',

    sources_title: 'Sources',
    medical_terms_referenced: 'Medical Terms Referenced',
    no_terms: 'No indexed medical terms were detected in this report.',
    sources_disclaimer: 'This summary and term explanations were generated by AI for educational purposes. Wikipedia links are provided for general background reading and are not a substitute for advice from a licensed healthcare professional.',

    analyze_another: 'Analyze another report',
    footer_disclaimer: 'This is not a medical diagnosis. Please consult a healthcare professional.',

    error_image_type: 'Please upload an image file (JPG, PNG, or PDF screenshot).',
    error_image_size: 'Image is too large. Please upload a file under 10 MB.',
    error_not_configured: 'The analysis service is not configured yet. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.',
    error_invalid_response: 'Received an invalid response from the analysis service.',
    error_generic: 'Something went wrong while analyzing your report. Please try again.',
  },

  // ── Hindi ────────────────────────────────────────────────────────────────────
  hi: {
    header_subtitle: 'अपनी रिपोर्ट समझें',
    start_over: 'फिर से शुरू करें',

    badge: 'AI-सहायक मेडिकल इमेजिंग',
    heading_lab: 'अपनी लैब रिपोर्ट को\nसरल भाषा में समझें',
    heading_xray: 'अपने X-ray को\nसरल भाषा में समझें',
    desc_lab: 'अपनी लैब रिपोर्ट की फ़ोटो अपलोड करें और स्पष्ट सारांश, असामान्य मान और डॉक्टर से पूछने के प्रश्न प्राप्त करें।',
    desc_xray: 'X-ray की छवि अपलोड करें और सरल भाषा में जानें कि क्या दिखाई दे रहा है, चिंता के क्षेत्र और डॉक्टर से पूछने के प्रश्न।',

    toggle_lab: 'लैब रिपोर्ट',
    toggle_xray: 'X-Ray',

    upload_lab: 'रिपोर्ट अपलोड करने के लिए टैप करें',
    upload_xray: 'X-ray अपलोड करने के लिए टैप करें',
    drag_drop: 'या यहाँ खींचकर छोड़ें',
    file_hint: 'JPG, PNG \u00b7 10 MB तक',

    badge_private: 'निजी और सुरक्षित',
    badge_instant: 'तत्काल विश्लेषण',
    badge_plain: 'सरल भाषा',

    lang_label: 'भाषा',

    analyze_lab: 'रिपोर्ट का विश्लेषण करें',
    analyze_xray: 'X-Ray का विश्लेषण करें',
    analyzing_lab: 'आपकी रिपोर्ट का विश्लेषण हो रहा है\u2026',
    analyzing_xray: 'आपके X-ray का विश्लेषण हो रहा है\u2026',
    steps_lab: ['छवि से पाठ निकाला जा रहा है', 'AI को विश्लेषण के लिए भेजा जा रहा है', 'असामान्य मानों की पहचान की जा रही है', 'आपका सारांश तैयार हो रहा है'],
    steps_xray: ['X-ray छवि प्रोसेस की जा रही है', 'AI रेडियोलॉजिस्ट को भेजा जा रहा है', 'चिंता के क्षेत्र पहचाने जा रहे हैं', 'आपकी व्याख्या तैयार हो रही है'],
    try_again: 'फिर से प्रयास करें',

    your_report: 'आपकी रिपोर्ट',
    file_name_fallback: 'अपलोड की गई रिपोर्ट',
    analysis_complete: 'विश्लेषण पूर्ण',
    new_report: 'नई रिपोर्ट',

    health_risk: 'स्वास्थ्य जोखिम',
    risk_low: 'कम जोखिम',
    risk_moderate: 'मध्यम जोखिम',
    risk_high: 'उच्च जोखिम',

    key_findings: 'मुख्य निष्कर्ष',
    severity_normal: 'सामान्य',
    severity_monitor: 'निगरानी',
    severity_attention: 'ध्यान दें',

    report_summary: 'रिपोर्ट सारांश',

    abnormal_values: 'असामान्य मान',
    no_abnormal: 'कोई असामान्य मान नहीं मिला। सभी परिणाम सामान्य सीमा के भीतर हैं।',
    normal_range: 'सामान्य सीमा:',

    questions_title: 'डॉक्टर से पूछने के प्रश्न',
    questions_subtitle: 'ये प्रश्न अपनी अगली मुलाकात में लेकर जाएं।',

    disclaimer_title: 'अस्वीकरण',
    disclaimer_1: 'यह कोई चिकित्सा निदान नहीं है। कृपया स्वास्थ्य पेशेवर से परामर्श लें।',
    disclaimer_2: 'MediExplain एक सूचनात्मक उपकरण है, कोई चिकित्सा उपकरण नहीं। यह निदान, उपचार या पेशेवर चिकित्सा सलाह का विकल्प नहीं करता।',
    disclaimer_3: 'विश्लेषण AI द्वारा शैक्षिक उद्देश्यों के लिए तैयार किया गया है और इसमें त्रुटियाँ हो सकती हैं। स्वास्थ्य संबंधी निर्णय लेने से पहले हमेशा किसी लाइसेंस प्राप्त स्वास्थ्य सेवा प्रदाता से परामर्श करें।',
    disclaimer_4: 'इस उपकरण का उपयोग करके आप स्वीकार करते हैं कि यह आउटपुट पेशेवर चिकित्सा मूल्यांकन का विकल्प नहीं है।',

    sources_title: 'स्रोत',
    medical_terms_referenced: 'संदर्भित चिकित्सा शब्द',
    no_terms: 'इस रिपोर्ट में कोई अनुक्रमित चिकित्सा शब्द नहीं मिला।',
    sources_disclaimer: 'यह सारांश और शब्द स्पष्टीकरण AI द्वारा शैक्षिक उद्देश्यों के लिए तैयार किए गए हैं। Wikipedia लिंक सामान्य पृष्ठभूमि पढ़ने के लिए दिए गए हैं और लाइसेंस प्राप्त स्वास्थ्य पेशेवर की सलाह का विकल्प नहीं हैं।',

    analyze_another: 'एक और रिपोर्ट का विश्लेषण करें',
    footer_disclaimer: 'यह कोई चिकित्सा निदान नहीं है। कृपया स्वास्थ्य पेशेवर से परामर्श लें।',

    error_image_type: 'कृपया एक छवि फ़ाइल अपलोड करें (JPG, PNG, या PDF स्क्रीनशॉट)।',
    error_image_size: 'छवि बहुत बड़ी है। कृपया 10 MB से कम की फ़ाइल अपलोड करें।',
    error_not_configured: 'विश्लेषण सेवा अभी कॉन्फ़िगर नहीं है। कृपया VITE_SUPABASE_URL और VITE_SUPABASE_ANON_KEY सेट करें।',
    error_invalid_response: 'विश्लेषण सेवा से अमान्य प्रतिक्रिया मिली।',
    error_generic: 'रिपोर्ट का विश्लेषण करते समय कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
  },

  // ── Tamil ────────────────────────────────────────────────────────────────────
  ta: {
    header_subtitle: 'உங்கள் அறிக்கையை புரிந்துகொள்ளுங்கள்',
    start_over: 'மீண்டும் தொடங்கு',

    badge: 'AI-உதவி மருத்துவ படமெடுத்தல்',
    heading_lab: 'உங்கள் ஆய்வக அறிக்கையை\nஎளிய மொழியில் புரிந்துகொள்ளுங்கள்',
    heading_xray: 'உங்கள் X-ray-ஐ\nஎளிய மொழியில் புரிந்துகொள்ளுங்கள்',
    desc_lab: 'உங்கள் ஆய்வக அறிக்கையின் படத்தை பதிவேற்றவும், தெளிவான சுருக்கம், அசாதாரண மதிப்புகள் மற்றும் மருத்துவரிடம் கேட்க வேண்டிய கேள்விகளைப் பெறுங்கள்.',
    desc_xray: 'X-ray படத்தை பதிவேற்றவும், என்ன தெரிகிறது என்ற விளக்கம், கவலைப்படும் பகுதிகள் மற்றும் மருத்துவரிடம் கேட்க வேண்டிய கேள்விகளைப் பெறுங்கள்.',

    toggle_lab: 'ஆய்வக அறிக்கை',
    toggle_xray: 'X-Ray',

    upload_lab: 'அறிக்கையை பதிவேற்ற தட்டவும்',
    upload_xray: 'X-ray-ஐ பதிவேற்ற தட்டவும்',
    drag_drop: 'அல்லது இங்கே இழுத்து விடுங்கள்',
    file_hint: 'JPG, PNG \u00b7 10 MB வரை',

    badge_private: 'தனிப்பட்ட மற்றும் பாதுகாப்பான',
    badge_instant: 'உடனடி பகுப்பாய்வு',
    badge_plain: 'எளிய மொழி',

    lang_label: 'மொழி',

    analyze_lab: 'அறிக்கையை பகுப்பாய்வு செய்யுங்கள்',
    analyze_xray: 'X-Ray-ஐ பகுப்பாய்வு செய்யுங்கள்',
    analyzing_lab: 'உங்கள் அறிக்கை பகுப்பாய்வு செய்யப்படுகிறது\u2026',
    analyzing_xray: 'உங்கள் X-ray பகுப்பாய்வு செய்யப்படுகிறது\u2026',
    steps_lab: ['படத்திலிருந்து உரை பிரிக்கப்படுகிறது', 'AI-க்கு பகுப்பாய்வுக்கு அனுப்பப்படுகிறது', 'அசாதாரண மதிப்புகள் கண்டறியப்படுகின்றன', 'உங்கள் சுருக்கம் தயார் செய்யப்படுகிறது'],
    steps_xray: ['X-ray படம் செயலாக்கப்படுகிறது', 'AI கதிரியக்க நிபுணருக்கு அனுப்பப்படுகிறது', 'கவலைப்படும் பகுதிகள் கண்டறியப்படுகின்றன', 'உங்கள் விளக்கம் தயார் செய்யப்படுகிறது'],
    try_again: 'மீண்டும் முயற்சி செய்யுங்கள்',

    your_report: 'உங்கள் அறிக்கை',
    file_name_fallback: 'பதிவேற்றப்பட்ட அறிக்கை',
    analysis_complete: 'பகுப்பாய்வு முடிந்தது',
    new_report: 'புதிய அறிக்கை',

    health_risk: 'உடல்நல ஆபத்து',
    risk_low: 'குறைந்த ஆபத்து',
    risk_moderate: 'மிதமான ஆபத்து',
    risk_high: 'அதிக ஆபத்து',

    key_findings: 'முக்கிய கண்டுபிடிப்புகள்',
    severity_normal: 'சாதாரண',
    severity_monitor: 'கண்காணிக்கவும்',
    severity_attention: 'கவனம்',

    report_summary: 'அறிக்கை சுருக்கம்',

    abnormal_values: 'அசாதாரண மதிப்புகள்',
    no_abnormal: 'அசாதாரண மதிப்புகள் எதுவும் கண்டறியப்படவில்லை. அனைத்து முடிவுகளும் சாதாரண வரம்பிற்குள் உள்ளன.',
    normal_range: 'சாதாரண வரம்பு:',

    questions_title: 'மருத்துவரிடம் கேட்க வேண்டிய கேள்விகள்',
    questions_subtitle: 'இந்த கேள்விகளை உங்கள் அடுத்த சந்திப்பில் கேளுங்கள்.',

    disclaimer_title: 'மறுப்பு',
    disclaimer_1: 'இது ஒரு மருத்துவ நோயறிதல் அல்ல. தயவுசெய்து ஒரு சுகாதார நிபுணரை அணுகுங்கள்.',
    disclaimer_2: 'MediExplain ஒரு தகவல் கருவியாகும், மருத்துவ சாதனம் அல்ல. இது நோயை கண்டறிவது, சிகிச்சையளிப்பது அல்லது தொழில்முறை மருத்துவ ஆலோசனையை மாற்றுவது அல்ல.',
    disclaimer_3: 'பகுப்பாய்வு AI ஆல் கல்வி நோக்கங்களுக்காக உருவாக்கப்பட்டது, தவறுகள் இருக்கலாம். உடல்நலம் குறித்த முடிவுகளை எடுக்கும் முன் எப்போதும் உரிமம் பெற்ற சுகாதார வழங்குநரை அணுகுங்கள்.',
    disclaimer_4: 'இந்த கருவியை பயன்படுத்துவதன் மூலம் வெளியீடு தொழில்முறை மருத்துவ மதிப்பீட்டிற்கு மாற்றாக இல்லை என்று நீங்கள் ஒப்புக்கொள்கிறீர்கள்.',

    sources_title: 'ஆதாரங்கள்',
    medical_terms_referenced: 'குறிப்பிடப்பட்ட மருத்துவ சொற்கள்',
    no_terms: 'இந்த அறிக்கையில் அட்டவணைப்படுத்தப்பட்ட மருத்துவ சொற்கள் எதுவும் கண்டறியப்படவில்லை.',
    sources_disclaimer: 'இந்த சுருக்கம் மற்றும் சொல் விளக்கங்கள் AI ஆல் கல்வி நோக்கங்களுக்காக உருவாக்கப்பட்டன. Wikipedia இணைப்புகள் பொது பின்னணி வாசிப்புக்காக வழங்கப்பட்டுள்ளன, உரிமம் பெற்ற சுகாதார நிபுணரின் ஆலோசனைக்கு மாற்றாக இல்லை.',

    analyze_another: 'மற்றொரு அறிக்கையை பகுப்பாய்வு செய்யுங்கள்',
    footer_disclaimer: 'இது ஒரு மருத்துவ நோயறிதல் அல்ல. தயவுசெய்து ஒரு சுகாதார நிபுணரை அணுகுங்கள்.',

    error_image_type: 'தயவுசெய்து ஒரு படக் கோப்பை பதிவேற்றவும் (JPG, PNG, அல்லது PDF ஸ்கிரீன்ஷாட்).',
    error_image_size: 'படம் மிகவும் பெரியது. தயவுசெய்து 10 MB-க்கு கீழ் உள்ள கோப்பை பதிவேற்றவும்.',
    error_not_configured: 'பகுப்பாய்வு சேவை இன்னும் கட்டமைக்கப்படவில்லை. VITE_SUPABASE_URL மற்றும் VITE_SUPABASE_ANON_KEY அமைக்கவும்.',
    error_invalid_response: 'பகுப்பாய்வு சேவையிலிருந்து தவறான பதில் கிடைத்தது.',
    error_generic: 'அறிக்கையை பகுப்பாய்வு செய்யும்போது பிழை ஏற்பட்டது. மீண்டும் முயற்சி செய்யுங்கள்.',
  },
};
